# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.7

sudo: enabled
dist: xenial

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y coinor-cbc

install: pip install .

script: pytest


